version: "3.7"
services:

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    restart: always
    ports:
      - "9091:9091"
#    network_mode: host
    volumes:
      - ./pushgateway:/etc/pushgateway/
    command:
      - '--web.config.file=/etc/pushgateway/${PUSH_GATEWAY_CONFIG_FILENAME}'
    labels:
      org.label-schema.group: "monitoring"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
      - ./prometheus_data:/data/prometheus/data
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/${PROMETHEUS_CONFIG_FILENAME}
      - --storage.tsdb.retention.time=90d
      - --storage.tsdb.path=/data/prometheus/data
    ports:
      - "9090:9090"
#    network_mode: host
    restart: always
    environment:
      TZ: "Asia/Almaty"

  grafana:
    image: grafana/grafana
    user: root
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
#    network_mode: host
    volumes:
      - ./grafana_data/grafana:/var/lib/grafana
      - ./grafana_data/grafana-provisioning:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    restart: always
    environment:
      TZ: "Asia/Almaty"
