scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
#      - targets: ['node-exporter:9100']
      - targets: ['localhost:9100']
  - job_name: gmlc
    scrape_interval: 5s
    metrics_path: /prometheus
    static_configs:
      - targets: ['localhost:8080']
